import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideHeader from "@/app/shared/SideHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " Employee Information",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <SideHeader />
        <div className="lg:pl-[340px] sm:pl-36 sm:pr-5 px-5 max-w-7xl">{children}</div>
      </body>
    </html>
  );
}
